// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD94O9WunSUeNWeGvK2DCAB59RnoszwgLg',
    appId: '1:154080982900:web:77dbf529b9c6875270de21',
    messagingSenderId: '154080982900',
    projectId: 'a-53358',
    authDomain: 'a-53358.firebaseapp.com',
    storageBucket: 'a-53358.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCecvoMN_ZT0JD7-5Xo2SueeJcHmxQ_ETU',
    appId: '1:154080982900:android:14ff7d7c369b01f370de21',
    messagingSenderId: '154080982900',
    projectId: 'a-53358',
    storageBucket: 'a-53358.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzYJGH_3-zIn5J5xMr-_4YXFONvvkTJkA',
    appId: '1:154080982900:ios:4a3c7bb8f9b63ec970de21',
    messagingSenderId: '154080982900',
    projectId: 'a-53358',
    storageBucket: 'a-53358.appspot.com',
    iosClientId: '154080982900-al8rfb8dm71bpgud7a8u1l0qgcrsmgop.apps.googleusercontent.com',
    iosBundleId: 'com.example.amazona',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzYJGH_3-zIn5J5xMr-_4YXFONvvkTJkA',
    appId: '1:154080982900:ios:5b04d1825a0f010a70de21',
    messagingSenderId: '154080982900',
    projectId: 'a-53358',
    storageBucket: 'a-53358.appspot.com',
    iosClientId: '154080982900-742l15028c8mhb68cath6rrfoalh7b7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.amazona.RunnerTests',
  );
}
